<?php
// Tablas: portfolio, products, services, shipping, settings, users
return [
    'portfolio' => ['columns' => [
        'id' => 'int NOT NULL AUTO_INCREMENT PRIMARY KEY',
        'name' => 'varchar(255) NOT NULL',
        'description' => 'text',
        'img_url' => 'varchar(500) NOT NULL',
        'created_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP',
    ]],
    'portfolio_items' => ['columns' => [
        'id' => 'int NOT NULL AUTO_INCREMENT PRIMARY KEY',
        'name' => 'varchar(255) NOT NULL',
        'description' => 'longtext',
        'img_url' => 'varchar(500) NOT NULL',
        'created_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP',
        'updated_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
    ]],
    'process_steps' => ['columns' => [
        'id' => 'int NOT NULL AUTO_INCREMENT PRIMARY KEY',
        'step_number' => 'int',
        'title' => 'varchar(255)',
        'description' => 'text',
        'img_url' => 'varchar(500)',
        'icon_name' => 'varchar(100)',
        'created_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP',
        'updated_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
    ]],
    'product_categories' => ['columns' => [
        'id' => 'int NOT NULL AUTO_INCREMENT PRIMARY KEY',
        'name' => 'varchar(255) NOT NULL',
        'slug' => 'varchar(255) UNIQUE',
        'description' => 'text',
        'parent_id' => 'int',
        'image_url' => 'varchar(500)',
        'display_order' => 'int DEFAULT 0',
        'status' => "enum('active','inactive') DEFAULT 'active'",
        'created_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP',
        'updated_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
    ]],
    'product_variations' => ['columns' => [
        'id' => 'int NOT NULL AUTO_INCREMENT PRIMARY KEY',
        'product_id' => 'int NOT NULL',
        'sku' => 'varchar(100)',
        'price' => 'decimal(10,2)',
        'sale_price' => 'decimal(10,2)',
        'stock_quantity' => 'int DEFAULT 0',
        'stock_status' => "enum('instock','outofstock','onbackorder') DEFAULT 'instock'",
        'attributes' => 'json',
        'image_url' => 'varchar(500)',
        'display_order' => 'int DEFAULT 0',
        'status' => "enum('active','inactive') DEFAULT 'active'",
        'created_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP',
        'updated_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
    ]],
    'product_views' => ['columns' => [
        'id' => 'int NOT NULL AUTO_INCREMENT PRIMARY KEY',
        'product_id' => 'int NOT NULL',
        'user_id' => 'int',
        'session_id' => 'varchar(255)',
        'ip_address' => 'varchar(45)',
        'user_agent' => 'text',
        'referrer' => 'varchar(500)',
        'viewed_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP',
    ]],
    'products' => ['columns' => [
        'id' => 'int NOT NULL AUTO_INCREMENT PRIMARY KEY',
        'name' => 'varchar(255) NOT NULL',
        'slug' => 'varchar(255) UNIQUE',
        'description' => 'longtext',
        'short_description' => 'text',
        'sku' => 'varchar(100) UNIQUE',
        'price' => 'decimal(10,2) NOT NULL DEFAULT 0',
        'sale_price' => 'decimal(10,2)',
        'stock_quantity' => 'int DEFAULT 0',
        'stock_status' => "enum('instock','outofstock','onbackorder') DEFAULT 'instock'",
        'weight' => 'decimal(5,2)',
        'dimensions' => 'varchar(100)',
        'category_id' => 'int',
        'image_url' => 'varchar(500)',
        'gallery_images' => 'json',
        'attributes' => 'json',
        'tags' => 'json',
        'seo_title' => 'varchar(255)',
        'seo_description' => 'text',
        'status' => "enum('publish','draft','trash') DEFAULT 'draft'",
        'product_type' => "enum('service','physical') DEFAULT 'physical'",
        'requires_shipping' => 'tinyint(1) DEFAULT 1',
        'service_category' => 'varchar(100)',
        'service_duration_minutes' => 'int',
        'service_mode' => "enum('online','presencial','mixto')",
        'featured' => 'tinyint(1) DEFAULT 0',
        'virtual' => 'tinyint(1) DEFAULT 0',
        'downloadable' => 'tinyint(1) DEFAULT 0',
        'created_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP',
        'updated_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
    ]],
    'search_queries' => ['columns' => [
        'id' => 'int NOT NULL AUTO_INCREMENT PRIMARY KEY',
        'query' => 'varchar(255)',
        'results_count' => 'int DEFAULT 0',
        'user_id' => 'int',
        'session_id' => 'varchar(255)',
        'ip_address' => 'varchar(45)',
        'user_agent' => 'text',
        'searched_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP',
    ]],
    'services' => ['columns' => [
        'id' => 'int NOT NULL AUTO_INCREMENT PRIMARY KEY',
        'title' => 'varchar(255) NOT NULL',
        'description' => 'text',
        'category' => 'varchar(100)',
        'main_image_url' => 'varchar(500)',
        'created_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP',
        'icon_name' => 'varchar(100)',
        'price' => 'decimal(10,2)',
        'featured' => 'tinyint(1) DEFAULT 0',
        'display_order' => 'int DEFAULT 0',
        'updated_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
    ]],
    'shipping_methods' => ['columns' => [
        'id' => 'int NOT NULL AUTO_INCREMENT PRIMARY KEY',
        'zone_id' => 'int',
        'name' => 'varchar(255) NOT NULL',
        'description' => 'text',
        'method_type' => "enum('flat_rate','free_shipping','local_pickup') DEFAULT 'flat_rate'",
        'cost' => 'decimal(10,2) DEFAULT 0',
        'min_amount' => 'decimal(10,2)',
        'max_weight' => 'decimal(5,2)',
        'status' => "enum('active','inactive') DEFAULT 'active'",
        'created_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP',
        'updated_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
    ]],
    'shipping_zones' => ['columns' => [
        'id' => 'int NOT NULL AUTO_INCREMENT PRIMARY KEY',
        'name' => 'varchar(255) NOT NULL',
        'countries' => 'json',
        'created_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP',
        'updated_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
    ]],
    'site_lists' => ['columns' => [
        'id' => 'int NOT NULL AUTO_INCREMENT PRIMARY KEY',
        'list_key' => 'varchar(50) NOT NULL',
        'item_value' => 'varchar(255) NOT NULL',
    ]],
    'site_settings' => ['columns' => [
        'id' => 'int NOT NULL AUTO_INCREMENT PRIMARY KEY',
        'setting_key' => 'varchar(255) NOT NULL UNIQUE',
        'setting_value' => 'longtext',
        'updated_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
    ]],
    'user_addresses' => ['columns' => [
        'id' => 'int NOT NULL AUTO_INCREMENT PRIMARY KEY',
        'user_id' => 'int',
        'type' => "enum('billing','shipping') DEFAULT 'billing'",
        'first_name' => 'varchar(100)',
        'last_name' => 'varchar(100)',
        'company' => 'varchar(100)',
        'address_1' => 'varchar(255)',
        'address_2' => 'varchar(255)',
        'city' => 'varchar(100)',
        'state' => 'varchar(100)',
        'postcode' => 'varchar(20)',
        'country' => 'varchar(2)',
        'phone' => 'varchar(50)',
        'email' => 'varchar(255)',
        'is_default' => 'tinyint(1) DEFAULT 0',
        'created_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP',
        'updated_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
    ]],
    'users' => ['columns' => [
        'id' => 'int NOT NULL AUTO_INCREMENT PRIMARY KEY',
        'name' => 'varchar(255) NOT NULL',
        'email' => 'varchar(255) NOT NULL UNIQUE',
        'password_hash' => 'varchar(255)',
        'phone' => 'varchar(50)',
        'avatar' => 'varchar(500)',
        'email_verified' => 'tinyint(1) DEFAULT 0',
        'created_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP',
        'updated_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
    ]],
    'contact_messages' => ['columns' => [
        'id' => 'int NOT NULL AUTO_INCREMENT PRIMARY KEY',
        'name' => 'varchar(255) NOT NULL',
        'email' => 'varchar(255) NOT NULL',
        'phone' => 'varchar(50)',
        'subject' => 'varchar(255)',
        'message' => 'text NOT NULL',
        'read_at' => 'datetime',
        'created_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP',
    ]],
];
