<?php
/**
 * Katy & Woof - Schema Definition
 * Esquema ideal de la base de datos para auditoría y sincronización.
 */
return [
    'blog_posts' => ['columns' => [
        'id' => 'int NOT NULL AUTO_INCREMENT PRIMARY KEY',
        'title' => 'varchar(255) NOT NULL',
        'content' => 'text',
        'category' => 'varchar(100) DEFAULT \'General\'',
        'img_url' => 'varchar(500) NOT NULL',
        'created_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP',
        'slug' => 'varchar(255)',
        'excerpt' => 'varchar(500)',
        'featured_image' => 'varchar(500)',
        'author' => 'varchar(100)',
        'views_count' => 'int DEFAULT 0',
        'published' => 'tinyint(1) DEFAULT 0',
        'published_at' => 'datetime',
        'updated_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
    ]],
    'cart_items' => ['columns' => [
        'id' => 'int NOT NULL AUTO_INCREMENT PRIMARY KEY',
        'session_id' => 'varchar(255)',
        'user_id' => 'int',
        'product_id' => 'int NOT NULL',
        'variation_id' => 'int',
        'quantity' => 'int NOT NULL DEFAULT 1',
        'price' => 'decimal(10,2)',
        'line_total' => 'decimal(10,2)',
        'added_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP',
        'updated_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
    ]],
    'coupons' => ['columns' => [
        'id' => 'int NOT NULL AUTO_INCREMENT PRIMARY KEY',
        'code' => 'varchar(50) NOT NULL UNIQUE',
        'description' => 'text',
        'discount_type' => 'enum(\'fixed\',\'percentage\')',
        'discount_value' => 'decimal(10,2)',
        'usage_limit' => 'int',
        'usage_count' => 'int DEFAULT 0',
        'expiry_date' => 'date',
        'minimum_amount' => 'decimal(10,2)',
        'maximum_amount' => 'decimal(10,2)',
        'product_ids' => 'json',
        'category_ids' => 'json',
        'exclude_product_ids' => 'json',
        'exclude_category_ids' => 'json',
        'individual_use' => 'tinyint(1) DEFAULT 0',
        'status' => 'enum(\'active\',\'inactive\') DEFAULT \'active\'',
        'created_by' => 'int',
        'created_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP',
        'updated_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
    ]],
    'ecommerce_settings' => ['columns' => [
        'id' => 'int NOT NULL AUTO_INCREMENT PRIMARY KEY',
        'setting_key' => 'varchar(100) NOT NULL UNIQUE',
        'setting_value' => 'longtext',
        'setting_group' => 'varchar(50)',
        'setting_type' => 'enum(\'string\',\'number\',\'boolean\',\'json\',\'array\') DEFAULT \'string\'',
        'is_public' => 'tinyint(1) DEFAULT 0',
        'created_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP',
        'updated_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
    ]],
    'list_items' => ['columns' => [
        'id' => 'int NOT NULL AUTO_INCREMENT PRIMARY KEY',
        'list_key' => 'varchar(100) NOT NULL',
        'item_value' => 'varchar(255) NOT NULL',
        'item_order' => 'int DEFAULT 0',
        'created_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP',
        'updated_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
    ]],
    'logs' => ['columns' => [
        'id' => 'int NOT NULL AUTO_INCREMENT PRIMARY KEY',
        'event_type' => 'varchar(100)',
        'message' => 'longtext',
        'ip_address' => 'varchar(45)',
        'user_agent' => 'varchar(500)',
        'created_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP',
    ]],
    'order_coupons' => ['columns' => [
        'id' => 'int NOT NULL AUTO_INCREMENT PRIMARY KEY',
        'order_id' => 'int NOT NULL',
        'coupon_id' => 'int',
        'coupon_code' => 'varchar(50)',
        'discount_amount' => 'decimal(10,2)',
        'created_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP',
    ]],
    'order_items' => ['columns' => [
        'id' => 'int NOT NULL AUTO_INCREMENT PRIMARY KEY',
        'order_id' => 'int NOT NULL',
        'product_id' => 'int',
        'variation_id' => 'int',
        'product_name' => 'varchar(255)',
        'product_sku' => 'varchar(100)',
        'quantity' => 'int NOT NULL DEFAULT 1',
        'price' => 'decimal(10,2)',
        'line_total' => 'decimal(10,2)',
        'line_tax' => 'decimal(10,2) DEFAULT 0',
        'variation_data' => 'json',
        'created_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP',
    ]],
    'order_status_history' => ['columns' => [
        'id' => 'int NOT NULL AUTO_INCREMENT PRIMARY KEY',
        'order_id' => 'int NOT NULL',
        'old_status' => 'enum(\'pending\',\'processing\',\'shipped\',\'completed\',\'cancelled\',\'refunded\',\'failed\')',
        'new_status' => 'enum(\'pending\',\'processing\',\'shipped\',\'completed\',\'cancelled\',\'refunded\',\'failed\')',
        'notes' => 'text',
        'changed_by' => 'int',
        'created_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP',
    ]],
    'orders' => ['columns' => [
        'id' => 'int NOT NULL AUTO_INCREMENT PRIMARY KEY',
        'order_number' => 'varchar(50) UNIQUE',
        'user_id' => 'int',
        'customer_email' => 'varchar(255)',
        'customer_data' => 'json',
        'status' => 'enum(\'pending\',\'processing\',\'shipped\',\'completed\',\'cancelled\',\'refunded\',\'failed\') DEFAULT \'pending\'',
        'currency' => 'varchar(3) DEFAULT \'CLP\'',
        'subtotal' => 'decimal(10,2) DEFAULT 0',
        'tax_total' => 'decimal(10,2) DEFAULT 0',
        'shipping_total' => 'decimal(10,2) DEFAULT 0',
        'discount_total' => 'decimal(10,2) DEFAULT 0',
        'total' => 'decimal(10,2) DEFAULT 0',
        'payment_method' => 'varchar(50)',
        'payment_status' => 'enum(\'pending\',\'paid\',\'failed\',\'refunded\',\'cancelled\') DEFAULT \'pending\'',
        'transaction_id' => 'varchar(255)',
        'flow_order_id' => 'varchar(255)',
        'shipping_method' => 'varchar(100)',
        'shipping_address' => 'json',
        'billing_address' => 'json',
        'order_notes' => 'text',
        'customer_ip' => 'varchar(45)',
        'user_agent' => 'text',
        'created_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP',
        'updated_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
    ]],
    'portfolio' => ['columns' => [
        'id' => 'int NOT NULL AUTO_INCREMENT PRIMARY KEY',
        'name' => 'varchar(255) NOT NULL',
        'description' => 'text',
        'img_url' => 'varchar(500) NOT NULL',
        'created_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP',
    ]],
    'portfolio_items' => ['columns' => [
        'id' => 'int NOT NULL AUTO_INCREMENT PRIMARY KEY',
        'name' => 'varchar(255) NOT NULL',
        'description' => 'longtext',
        'img_url' => 'varchar(500) NOT NULL',
        'created_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP',
        'updated_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
    ]],
    'process_steps' => ['columns' => [
        'id' => 'int NOT NULL AUTO_INCREMENT PRIMARY KEY',
        'step_number' => 'int',
        'title' => 'varchar(255)',
        'description' => 'text',
        'img_url' => 'varchar(500)',
        'icon_name' => 'varchar(100)',
        'created_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP',
        'updated_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
    ]],
    'product_categories' => ['columns' => [
        'id' => 'int NOT NULL AUTO_INCREMENT PRIMARY KEY',
        'name' => 'varchar(255) NOT NULL',
        'slug' => 'varchar(255) UNIQUE',
        'description' => 'text',
        'parent_id' => 'int',
        'image_url' => 'varchar(500)',
        'display_order' => 'int DEFAULT 0',
        'status' => 'enum(\'active\',\'inactive\') DEFAULT \'active\'',
        'created_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP',
        'updated_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
    ]],
    'product_variations' => ['columns' => [
        'id' => 'int NOT NULL AUTO_INCREMENT PRIMARY KEY',
        'product_id' => 'int NOT NULL',
        'sku' => 'varchar(100)',
        'price' => 'decimal(10,2)',
        'sale_price' => 'decimal(10,2)',
        'stock_quantity' => 'int DEFAULT 0',
        'stock_status' => 'enum(\'instock\',\'outofstock\',\'onbackorder\') DEFAULT \'instock\'',
        'attributes' => 'json',
        'image_url' => 'varchar(500)',
        'display_order' => 'int DEFAULT 0',
        'status' => 'enum(\'active\',\'inactive\') DEFAULT \'active\'',
        'created_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP',
        'updated_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
    ]],
    'product_views' => ['columns' => [
        'id' => 'int NOT NULL AUTO_INCREMENT PRIMARY KEY',
        'product_id' => 'int NOT NULL',
        'user_id' => 'int',
        'session_id' => 'varchar(255)',
        'ip_address' => 'varchar(45)',
        'user_agent' => 'text',
        'referrer' => 'varchar(500)',
        'viewed_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP',
    ]],
    'products' => ['columns' => [
        'id' => 'int NOT NULL AUTO_INCREMENT PRIMARY KEY',
        'name' => 'varchar(255) NOT NULL',
        'slug' => 'varchar(255) UNIQUE',
        'description' => 'longtext',
        'short_description' => 'text',
        'sku' => 'varchar(100) UNIQUE',
        'price' => 'decimal(10,2) NOT NULL DEFAULT 0',
        'sale_price' => 'decimal(10,2)',
        'stock_quantity' => 'int DEFAULT 0',
        'stock_status' => 'enum(\'instock\',\'outofstock\',\'onbackorder\') DEFAULT \'instock\'',
        'weight' => 'decimal(5,2)',
        'dimensions' => 'varchar(100)',
        'category_id' => 'int',
        'image_url' => 'varchar(500)',
        'gallery_images' => 'json',
        'attributes' => 'json',
        'tags' => 'json',
        'seo_title' => 'varchar(255)',
        'seo_description' => 'text',
        'status' => 'enum(\'publish\',\'draft\',\'trash\') DEFAULT \'draft\'',
        'product_type' => 'enum(\'service\',\'physical\') DEFAULT \'physical\'',
        'requires_shipping' => 'tinyint(1) DEFAULT 1',
        'service_category' => 'varchar(100)',
        'service_duration_minutes' => 'int',
        'service_mode' => 'enum(\'online\',\'presencial\',\'mixto\')',
        'featured' => 'tinyint(1) DEFAULT 0',
        'virtual' => 'tinyint(1) DEFAULT 0',
        'downloadable' => 'tinyint(1) DEFAULT 0',
        'created_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP',
        'updated_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
    ]],
    'search_queries' => ['columns' => [
        'id' => 'int NOT NULL AUTO_INCREMENT PRIMARY KEY',
        'query' => 'varchar(255)',
        'results_count' => 'int DEFAULT 0',
        'user_id' => 'int',
        'session_id' => 'varchar(255)',
        'ip_address' => 'varchar(45)',
        'user_agent' => 'text',
        'searched_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP',
    ]],
    'services' => ['columns' => [
        'id' => 'int NOT NULL AUTO_INCREMENT PRIMARY KEY',
        'title' => 'varchar(255) NOT NULL',
        'description' => 'text',
        'category' => 'varchar(100)',
        'main_image_url' => 'varchar(500)',
        'created_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP',
        'icon_name' => 'varchar(100)',
        'price' => 'decimal(10,2)',
        'featured' => 'tinyint(1) DEFAULT 0',
        'display_order' => 'int DEFAULT 0',
        'updated_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
    ]],
    'shipping_methods' => ['columns' => [
        'id' => 'int NOT NULL AUTO_INCREMENT PRIMARY KEY',
        'zone_id' => 'int',
        'name' => 'varchar(255) NOT NULL',
        'description' => 'text',
        'method_type' => 'enum(\'flat_rate\',\'free_shipping\',\'local_pickup\') DEFAULT \'flat_rate\'',
        'cost' => 'decimal(10,2) DEFAULT 0',
        'min_amount' => 'decimal(10,2)',
        'max_weight' => 'decimal(5,2)',
        'status' => 'enum(\'active\',\'inactive\') DEFAULT \'active\'',
        'created_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP',
        'updated_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
    ]],
    'shipping_zones' => ['columns' => [
        'id' => 'int NOT NULL AUTO_INCREMENT PRIMARY KEY',
        'name' => 'varchar(255) NOT NULL',
        'countries' => 'json',
        'created_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP',
        'updated_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
    ]],
    'site_lists' => ['columns' => [
        'id' => 'int NOT NULL AUTO_INCREMENT PRIMARY KEY',
        'list_key' => 'varchar(50) NOT NULL',
        'item_value' => 'varchar(255) NOT NULL',
    ]],
    'site_settings' => ['columns' => [
        'id' => 'int NOT NULL AUTO_INCREMENT PRIMARY KEY',
        'setting_key' => 'varchar(255) NOT NULL UNIQUE',
        'setting_value' => 'longtext',
        'updated_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
    ]],
    'user_addresses' => ['columns' => [
        'id' => 'int NOT NULL AUTO_INCREMENT PRIMARY KEY',
        'user_id' => 'int',
        'type' => 'enum(\'billing\',\'shipping\') DEFAULT \'billing\'',
        'first_name' => 'varchar(100)',
        'last_name' => 'varchar(100)',
        'company' => 'varchar(100)',
        'address_1' => 'varchar(255)',
        'address_2' => 'varchar(255)',
        'city' => 'varchar(100)',
        'state' => 'varchar(100)',
        'postcode' => 'varchar(20)',
        'country' => 'varchar(2)',
        'phone' => 'varchar(50)',
        'email' => 'varchar(255)',
        'is_default' => 'tinyint(1) DEFAULT 0',
        'created_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP',
        'updated_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
    ]],
];
