<?php
// Tablas: blog, cart, coupons, ecommerce_settings, list_items, logs, orders
return [
    'blog_posts' => ['columns' => [
        'id' => 'int NOT NULL AUTO_INCREMENT PRIMARY KEY',
        'title' => 'varchar(255) NOT NULL',
        'content' => 'text',
        'category' => "varchar(100) DEFAULT 'General'",
        'img_url' => 'varchar(500) NOT NULL',
        'created_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP',
        'slug' => 'varchar(255)',
        'excerpt' => 'varchar(500)',
        'featured_image' => 'varchar(500)',
        'author' => 'varchar(100)',
        'views_count' => 'int DEFAULT 0',
        'published' => 'tinyint(1) DEFAULT 0',
        'published_at' => 'datetime',
        'updated_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
    ]],
    'cart_items' => ['columns' => [
        'id' => 'int NOT NULL AUTO_INCREMENT PRIMARY KEY',
        'session_id' => 'varchar(255)',
        'user_id' => 'int',
        'product_id' => 'int NOT NULL',
        'variation_id' => 'int',
        'quantity' => 'int NOT NULL DEFAULT 1',
        'price' => 'decimal(10,2)',
        'line_total' => 'decimal(10,2)',
        'added_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP',
        'updated_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
    ]],
    'coupons' => ['columns' => [
        'id' => 'int NOT NULL AUTO_INCREMENT PRIMARY KEY',
        'code' => 'varchar(50) NOT NULL UNIQUE',
        'description' => 'text',
        'discount_type' => "enum('fixed','percentage')",
        'discount_value' => 'decimal(10,2)',
        'usage_limit' => 'int',
        'usage_count' => 'int DEFAULT 0',
        'expiry_date' => 'date',
        'minimum_amount' => 'decimal(10,2)',
        'maximum_amount' => 'decimal(10,2)',
        'product_ids' => 'json',
        'category_ids' => 'json',
        'exclude_product_ids' => 'json',
        'exclude_category_ids' => 'json',
        'individual_use' => 'tinyint(1) DEFAULT 0',
        'status' => "enum('active','inactive') DEFAULT 'active'",
        'created_by' => 'int',
        'created_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP',
        'updated_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
    ]],
    'ecommerce_settings' => ['columns' => [
        'id' => 'int NOT NULL AUTO_INCREMENT PRIMARY KEY',
        'setting_key' => 'varchar(100) NOT NULL UNIQUE',
        'setting_value' => 'longtext',
        'setting_group' => 'varchar(50)',
        'setting_type' => "enum('string','number','boolean','json','array') DEFAULT 'string'",
        'is_public' => 'tinyint(1) DEFAULT 0',
        'created_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP',
        'updated_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
    ]],
    'list_items' => ['columns' => [
        'id' => 'int NOT NULL AUTO_INCREMENT PRIMARY KEY',
        'list_key' => 'varchar(100) NOT NULL',
        'item_value' => 'varchar(255) NOT NULL',
        'item_order' => 'int DEFAULT 0',
        'created_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP',
        'updated_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
    ]],
    'logs' => ['columns' => [
        'id' => 'int NOT NULL AUTO_INCREMENT PRIMARY KEY',
        'event_type' => 'varchar(100)',
        'message' => 'longtext',
        'ip_address' => 'varchar(45)',
        'user_agent' => 'varchar(500)',
        'created_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP',
    ]],
    'order_coupons' => ['columns' => [
        'id' => 'int NOT NULL AUTO_INCREMENT PRIMARY KEY',
        'order_id' => 'int NOT NULL',
        'coupon_id' => 'int',
        'coupon_code' => 'varchar(50)',
        'discount_amount' => 'decimal(10,2)',
        'created_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP',
    ]],
    'order_items' => ['columns' => [
        'id' => 'int NOT NULL AUTO_INCREMENT PRIMARY KEY',
        'order_id' => 'int NOT NULL',
        'product_id' => 'int',
        'variation_id' => 'int',
        'product_name' => 'varchar(255)',
        'product_sku' => 'varchar(100)',
        'quantity' => 'int NOT NULL DEFAULT 1',
        'price' => 'decimal(10,2)',
        'line_total' => 'decimal(10,2)',
        'line_tax' => 'decimal(10,2) DEFAULT 0',
        'variation_data' => 'json',
        'created_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP',
    ]],
    'order_status_history' => ['columns' => [
        'id' => 'int NOT NULL AUTO_INCREMENT PRIMARY KEY',
        'order_id' => 'int NOT NULL',
        'old_status' => "enum('pending','processing','shipped','completed','cancelled','refunded','failed')",
        'new_status' => "enum('pending','processing','shipped','completed','cancelled','refunded','failed')",
        'notes' => 'text',
        'changed_by' => 'int',
        'created_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP',
    ]],
    'orders' => ['columns' => [
        'id' => 'int NOT NULL AUTO_INCREMENT PRIMARY KEY',
        'order_number' => 'varchar(50) UNIQUE',
        'user_id' => 'int',
        'customer_email' => 'varchar(255)',
        'customer_data' => 'json',
        'status' => "enum('pending','processing','shipped','completed','cancelled','refunded','failed') DEFAULT 'pending'",
        'currency' => "varchar(3) DEFAULT 'CLP'",
        'subtotal' => 'decimal(10,2) DEFAULT 0',
        'tax_total' => 'decimal(10,2) DEFAULT 0',
        'shipping_total' => 'decimal(10,2) DEFAULT 0',
        'discount_total' => 'decimal(10,2) DEFAULT 0',
        'total' => 'decimal(10,2) DEFAULT 0',
        'payment_method' => 'varchar(50)',
        'payment_status' => "enum('pending','paid','failed','refunded','cancelled') DEFAULT 'pending'",
        'transaction_id' => 'varchar(255)',
        'flow_order_id' => 'varchar(255)',
        'shipping_method' => 'varchar(100)',
        'shipping_address' => 'json',
        'billing_address' => 'json',
        'order_notes' => 'text',
        'customer_ip' => 'varchar(45)',
        'user_agent' => 'text',
        'created_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP',
        'updated_at' => 'timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
    ]],
];
